@baseUrl = http://localhost:3000

# @name get_image

GET {{baseUrl}}/camiseta-01.jpg
Content-Type: application/json


####

# @name get_products

GET {{baseUrl}}/products?
Content-Type: application/json


####

